### ISSUE TITLE
Task: Add update support for app insights

### ISSUE THREAD

**Issue by melonrush13** [Azure/azure-service-operator#1064]
In reference to bug #831 

Currently app insights does not have update support.
This ticket is to allow the user to update existing app insight resources.

**Done criteria**
- Create an app insights
- Apply a change (update `location:west us` -> `location: westus2`)
- View output yaml of app insights, should see updated location
- View app insights resource on Azure portal, should see updated location

**User story reference**

#<issue number of the user story that this task accrues to>

**Comment by sakthi-vetrivel** [comment]
This is complete!

**Comment by matthchr** [comment]
This is specifically talking about application insights components (the only appinsights resource ASO v1 supports).

Components are also supported in ASOv2 (added in #2000), and they support update. ASO v2 isn't quite in beta yet, but since ASO v1 is in maintenance mode and this isn't a critical bug or feature I'm going to close this.
