### ISSUE TITLE
Bug: Handle `InvalidApiVersionParameter` on Empty ResourceGroup / Gracefully handle 400 errs

### ISSUE THREAD

**Issue by melonrush13** [Azure/azure-service-operator#1106]
We should remove 'omitempty' from the types files for Resourcegroup from AzureSqlServer types. file and also other types if the issue exists. This will ensure that we catch the error if resourcegroup is not specified which causes this  issue.

**Describe the bug**

The following error occurs for creating a V1Alpha1 azuresqlserver with an empty resource group or invalid named resourcegroup.

```
"Error": "sql.ServersClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"InvalidApiVersionParameter\" Message=\"The api-version '2015-05-01-preview' is invalid. The supported versions are '2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.\"", "Instance": "default/sqlserver-sample-777"}
```

**To Reproduce**
`k create -f config/samples/azure_v1alpha1_azuresqlserver.yaml`
My Resource Group Name: `resourcegroup-azure-operators-mel`

**Expected behavior**
Gracefully handle 400 errors (similarly to how Redis Cache handles future errs)

**Screenshots**

**Additional context**

**Comment by jananivMS** [comment]
We should remove 'omitempty' from the types files for Resourcegroup from AzureSqlServer types. file and also other types if the issue exists. This will ensure that we catch the error if resourcegroup is not specified which causes this  issue.

**Comment by matthchr** [comment]
@melonrush13 were you testing this in kind, or in an AKS cluster with webhooks enabled?

This error definitely happens when `resourceGroup` is empty, but that's not actually possible based on the CRD (it's required for both `v1alpha1` and `v1beta`).  It's possible to get an `resourceGroup` string if you create a `v1alpha1` resource with webhooks disabled though (because conversion from v1alpha1 -> v1beta1 wasn't run).

I've filed [an issue](https://github.com/Azure/azure-sdk-for-go/issues/10712) for the Go SDK folks since the SDK is supposed to do this check, but in the meantime I've updated the controller to check this manually and give a better error in #1232132
