### ISSUE TITLE
Bug: Retention Policy with invalid values is able to create on Azure for AzureSqlDb

### ISSUE THREAD

**Issue by melonrush13** [Azure/azure-service-operator#1133]
**Describe the bug**
When creating a retention policy on AzureSqlDb, there are time restrictions such as "monthly must be set to 1 month", "weekly 1 week", etc.

If a user doesn't follow this pattern, and sets `monthlyRetention: P1W` it will successfully create and show in Azure (even tho Azure won't let you do this manually through the GUI)

**To Reproduce**
Create a retention policy on AzureSqlDatabase
Set `mothlyRetention: P1W`
View this on the Azure portal - should display successfully 

Try to create another monthly retention policy through the portal also set to 1 week.
GUI will not allow you to create

**Expected behavior**
We should do either of the following:
- Not allow provisioning of these retention policies to make it to Azure
- Provide comments in the yaml to avoid this situation happening
- Or suggestions welcome :)

**Screenshots**

**Additional context**

**Comment by matthchr** [comment]
This due to the fact that `RetentionPolicy` for SQL is actually a separate ARM resource, applying the spec is a multi-phase process because we must first apply the SQL spec and then apply the retention spec (it's not all one shot).

Because of that, it's possible to get into a "partially applied" state, where the SQL server has been created but the retention policy has not. Previously we were not conveying errors hit while applying the retention policy very well to the user but that has since been rectified.

The expected behavior here is that the SQL server exists in Azure, the policy also exists in Azure (they actually always exist whenever a server is created, with default values), but the P1W value was not actually applied to the policy.

In the future it is possible that we split policies out into their own resource as part of the code generation work being done (#1192).

There's also a test now for this case (invalid retention policy) in `azuresql_combined_test.go`.
