### ISSUE TITLE
Allow resource group-specific  RBAC / IAM 

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-service-operator#1194]
Hello folks! Looking thru this repo and thinking on use it for a greenfield project I'm about to start along with AAD pod identity one and I've stumped on the README to a curious statement:

> Note that the ServicePrincipal you pass to the command below needs to have access to create resources in your subscription.

That means, whatever ServicePrincipal (and I guess Managed Identity) used by ASO needs to have subscription-level Contributor role at least. That in some security-freak environments is far from ideal.

So, given that scenario, I wonder if it would be possible to allow the ServicePrincipal/MI to have only contributor writes on selected resource groups and not at the whole subscription.

I know that it would be something that would block the creation of the resource groups itself, but that would give people control on _where_ the resources created by the definitions being deployed would be and strip access for other unnecessary things.

Thanks!

**Comment by hlarubi** [comment]
Agreed. Would be useful for us as well.

**Comment by frodopwns** [comment]
Currently the operator can run with a Managed Identity instead of a Service Principal. The access required is generally baed on your use case. If you can make a managed Identity do a thing outside of ASO it should be doable within ASO as well.

That being said, most of my testing happens with a SP since it is easier for me. So if you jump in using MI and see issues just let me know and I can switch gears to address them.

One of my co-workers did a demo a couple months ago using MI and AAD Pod Identity.
https://github.com/Azure-Samples/azure-service-operator-samples/tree/master/azure-votes-cosmosdb

There may be something helpful in there for you.

**Comment by galvesribeiro** [comment]
Yes, I plan to use MI since everything else on our system will work on top of it. So the idea is to have some resource groups pre-created where the MI assigned to ASO will have contributor access so that way, it can create/delete those resources. 

Our setup should be AKS + ASO + Pod Identity.

I just want to make sure this will work as expected across the board.

**Comment by clarenceb** [comment]
Has anyone confirmed whether creating a SP scoped to a resource group will work?  I wouldn't want to allow it scoped to the subscription.

**Comment by babbageclunk** [comment]
Hi @clarenceb - I just checked, the operator can run with a resource-group-scoped SP and create resources in that group. It doesn't handle the error when

**Comment by babbageclunk** [comment]
I created the bug for this but hadn't linked it back to this.
