### ISSUE TITLE
Provide overview of image tags and Helm chart version

### ISSUE THREAD

**Issue by nmeisenzahl** [Azure/azure-service-operator#1239]
**Describe the current behavior**
At the moment it is hard to pin a specific version (image tag and/or helm chart version). The images, as well as Helm charts, are stored in an Azure Container Registry that does not allow easy access (like Docker Hub)

**Describe the improvement**
Either include the syntax of image tag and Helm chart versions somewhere in the documentation or add that information into the release notes.

**Comment by nmeisenzahl** [comment]
I guess this should be labeled with documentation. I'm unable to do so.

**Comment by matthchr** [comment]
We now pin automatically to a specific version of the operator container in the Helm chart, and there are new versions of the Helm chart any time a container or CRD update is released (you can see that here: https://github.com/Azure/azure-service-operator/tree/master/charts).

The operator YAML in releases if not using Helm is now also automatically pinned to the container version corresponding to the release (so [release 1.0.23694](https://github.com/Azure/azure-service-operator/releases/tag/1.0.23694) contains YAML with a container image pinned to version `1.0.23694` of the container.

We're looking at possibly syncing the Helm and non-Helm release path versions to further remove confusion, but in general you shouldn't have to worry about pinning much anymore because we just do it for you. You now fully control what version of ASO your cluster is running and can choose to upgrade when it works best for you.

Going to close this as I think the above addresses most of the issues brought up here, but if it doesn't or there are more issues feel free to request this reopened or file a new issue.
