### ISSUE TITLE
Bug: undeletable resources with permission errors

### ISSUE THREAD

**Issue by babbageclunk** [Azure/azure-service-operator#1273]
**Describe the bug**
If you use a resource-group-scoped service principal for the operator, and try to create resources outside of the scope group, the resources won't be provisioned in Azure, but the bad k8s resource also can't easily be deleted. The only way I could find was to use `kubectl edit <resource>` to remove the finalizers, which seems awkward.

**To Reproduce**
* Create an SP scoped to a resource group:
`az ad sp create-for-rbac -n "sp-name" --role contributor --scopes /subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/scoped-sp-group`
* Create a resource in a different resource group.
* Try to delete the resource.

**Expected behavior**
* We should be able to detect that we've never successfully provisioned the resource, so delete it from the API without having to delete it from ARM.

**Comment by babbageclunk** [comment]
Created while investigating #1194

**Comment by babbageclunk** [comment]
Once this behaviour is fixed we should also document that the identity used for the operator can be scoped narrower than the whole subscription.

**Comment by matthchr** [comment]
We should rephrase this issue and think about what we can do to mitigate/fix it in ASOv2

**Comment by matthchr** [comment]
Need to check if this is already fixed in ASOv2

**Comment by matthchr** [comment]
This problem can also happen in ASOv2.

Unfortunately it's hard to reliably fix as the minute we let a request fly for Azure, we accept the reality that it could have been accepted and triggered a resource creation. It's hard to put optimizations in like "if the request was accepted, mark that it was successfully accepted in the resource and if resource isn't marked then deletion just skips issuing a delete", because we need to be fault tolerant and this is a classic double-write problem (to Azure and etcd).

One thing we could do in ASOv2 to help prevent this problem at least for entire resource graphs is check the owners state in addition to its existence, so that we only get a single top level resource that's stuck while all the rest of the child resources are pending on the owner. Today we actually send requests to Azure for the whole graph and rely on Azure rejecting us.

**Comment by matthchr** [comment]
Oh wait, I am not correct. We already have this behavior in ASOv2, so at most the 1 owner resource will have this problem.

**Comment by matthchr** [comment]
Closing this. If a resource gets into this state in ASOv2 the easiest solution is to mark it with [reconcile-policy](https://azure.github.io/azure-service-operator/introduction/annotations/#serviceoperatorazurecomreconcile-policy) `skip` and then delete it.
