### ISSUE TITLE
Should failover group deletion also remove databases created on the secondary servers?

### ISSUE THREAD

**Issue by LukeCarrier** [Azure/azure-service-operator#1277]
**Describe the current behavior**

Creating a failover group requires that no database with the given name exists on the secondary servers, and will create new databases to serve as partners. On deletion these databases created by the failover group will remain present, which is consistent with the behaviour of the ARM API and other Azure clients.

**Describe the improvement**

For test deployments of an application including an Azure SQL Database, it would be convenient to have an option on the `AzureSqlFailoverGroup` resource allowing deletion of these secondary databases. At the moment we have to wrap `helm uninstall` with a script that cleans these resources up.

**Additional context**
N/A

**Comment by theunrepentantgeek** [comment]
Our current focus for ASO v2 is on faithfully reflecting ARM resources into Kubernetes, and we're not currently looking at layering additional functionality on top. This feature may require a non-trivial degree of change. 

ASO v1 is in maintenance mode and we're only addressing essential updates.

**Comment by matthchr** [comment]
We're still thinking about this, but no plan is in place yet.

**Comment by matthchr** [comment]
Still interested in doing this for ASOv2, but hasn't happened yet.

**Comment by matthchr** [comment]
Hey @LukeCarrier - it's been quite a while since this issue was opened and we haven't seen a lot of other users asking for this, at least yet. We are closing in on releasing ASO v2.0.0 and just wanted to touch base on this issue.

As @theunrepentantgeek mentioned above, our general philosophy is to "do what the ARM API does".  

You mentioned:
> At the moment we have to wrap helm uninstall with a script that cleans these resources up.

Could you not define the primary and secondary DB as resources in the Helm chart using the ASO CRDs? Then when Helm uninstall runs it will naturally delete the failoverGroup, and both DBs too, without any need for a special hook in ASO to do that automatically.

**Comment by LukeCarrier** [comment]
> Could you not define the primary and secondary DB as resources in the Helm chart using the ASO CRDs? Then when Helm uninstall runs it will naturally delete the failoverGroup, and both DBs too, without any need for a special hook in ASO to do that automatically.

Great question, but I suspect order of operations would then need testing.

Either way as I no longer work for an organisation using Azure this issue no longer affects me I'm afraid!
