### ISSUE TITLE
Feature: Blob storage CORS and lifecycle management

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/azure-service-operator#1322]
To set CORS rules for Blobs, it is required to be able to create and set properties on a Blob Services object: https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-service-properties

**Comment by matthchr** [comment]
This should be supported in ASO v2. We need to add a test to make sure it works though

**Comment by matthchr** [comment]
Actually on second look I don't really think a test specific to this is needed. It's part of the StorageAccountBlobServices resource that we already support.

**Comment by MattiasPernhult** [comment]
The title of this issue mentions both CORS and lifecycle management, I can see that former is supported in StorageAccountBlobServices but not the latter one. Any plans on adding support for lifecycle management?

**Comment by matthchr** [comment]
You are right @MattiasPernhult!

I had missed that because it wasn't actually discussed any in the body of the issue. Thanks for catching that. I've just filed #2114 that splits out the Lifecycle management stuff as it's a separate resource and we usually like to have a tracking item for entirely new resources.

**Comment by MattiasPernhult** [comment]
Great, thank you @matthchr, much appreciated!

**Comment by matthchr** [comment]
ASOv2 beta.0 has been released, closing this as this is supported there.
