### ISSUE TITLE
Bug: cert-manager doesn't work with Windows clusters

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/azure-service-operator#1329]
When installing Azure Service Operator into a cluster with a Windows nodepool, the cert-manager installation step fails, since cert-manager does not support Windows clusters. Need to either move away from using cert-manager, or provide workaround.

**Comment by sakthi-vetrivel** [comment]
@yunjunchoi

**Comment by sakthi-vetrivel** [comment]
@yunjchoi

**Comment by matthchr** [comment]
Was this a customer request?

We probably need to know more about full Windows clusters and what we can/cannot support as well.

This might end up becoming more of a documentation issue, since there may be no way for us to support hosting on Windows given some of our dependencies, etc.

**Comment by ds-evo** [comment]
add this to cert-manager, will schedule them on linux only:

```
  nodeSelector:
    kubernetes.io/os: Linux
```

**Comment by matthchr** [comment]
@ds-evo yes, exactly.

Right now we do not have a Helm chart for ASO v2 and so cannot set that setting automatically, but when we create one, we will fix that.

**Comment by super-harsh** [comment]
It looks like cert-manager doesn't support being installed with any chart other than its own (we can't include it as part of our installation) (see issue [cert-manager issue #3601](https://github.com/cert-manager/cert-manager/issues/3601)). 

On the topic of working out of the box on Windows there seem to be a bunch of topics discussing it in cert-manager and cannot be included as a sub-chart dependency in our helm installation(see issue [cert-manager issue #2964](https://github.com/cert-manager/cert-manager/pull/2964)).

Until the issue is solved upstream the best advice we can give is that users install cert manager and set nodeSelector to linux, we have a workaround for that which is by installing cert-manager helm chart standalone and set nodeSelector value while installing. Example below:
`helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --set nodeSelector."kubernetes\.io/role"=linux `
