### ISSUE TITLE
 create sub-folders in /config/samples/ based upon azure service for easier navigation.

### ISSUE THREAD

**Issue by williamohara** [Azure/azure-service-operator#1363]
pretty simple task - I could do it but not sure if that would make it easier for everyone. What do you think?

**Comment by sakthi-vetrivel** [comment]
@williamohara Totally agree. Feel free to take a crack at it if you get a chance before I do.

**Comment by matthchr** [comment]
Closing this. We'd be willing to take this change still but since our effort is primarily focused on V2 at this point it doesn't feel like it needs an issue tracking it.

We do this in V2 already as well, but good to see confirmation that others thought the flatter structure was a bit harder to parse.
