### ISSUE TITLE
Question: crossplane integration status update

### ISSUE THREAD

**Issue by Stijnc** [Azure/azure-service-operator#1774]
Hi,

Would it be possible to provide a status update on the crossplane integration?
the latest update dates from July 2020 in #1190

[The crossplane blog also mentions a converged effort](https://blog.crossplane.io/accelerating-crossplane-provider-coverage-with-ack-and-azure-code-generation-towards-100-percent-coverage-of-all-cloud-services/), but not sure if this is already in effect as the [crossplane azure provider](https://github.com/crossplane/provider-azure) is still being worked on? 

Appreciated!

**Comment by matthchr** [comment]
We have a Crossplane pipeline. You can see the the current status of some example generated types [here](https://github.com/Azure/azure-service-operator/tree/master/hack/crossplane/apis).

With that said, there are still a number of open issues that prevent those types from being used in Crossplane.

An incomplete list from the top of my head:
- Add support for ARM serialization (we have ~85% of the code for this, but given the Crossplane resources shape is different than for ASO it needs to be made to work generically across both shapes.
- We need to adapt the types so that they can plug into the Crossplane reconcilers interface.
- We will probably need to do a bit of work on resource ownership and cross resource references

There's probably more small things I am forgetting but those are at least some of the big rocks remaining. We're not currently focused on this effort although we are still in contact with the Crossplane team and will return to it eventually.

**Comment by Stijnc** [comment]
Thank you for the swift reply!
From the points taken above it is a safer bet to start adopting crossplane or do you see 2 different use cases?

**Comment by matthchr** [comment]
Are you asking about ASO vs Crossplane? There's some overlap (which is why we're working towards getting the same tool to produce CRDs for both), but they do have some key differences as well:

Do you need multi-cloud, or the ability to define your own higher level resources via Crossplane composition (with predefined defaults, limited choices, etc) that map onto the actual cloud resources? Then Crossplane probably makes more sense.

Do you want a simpler operator that just speaks that Azure API? Do you need more "official" MSFT support? Then at least currently ASO might fit your use case better.

At least currently there is no plan to merge or combine ASO and Crossplane's Azure provider. Our current thinking is that ASO is a lower level building block and that the Crossplane provider is part of a higher level (possibly more opinionated) solution. The north star goal is to either share types between ASO and Crossplane, or more likely share tooling that produces those types, so that both can build on the same foundation (which is itself sourced from [Azure's OpenAPI specs](https://github.com/Azure/azure-rest-api-specs)).

**Comment by Stijnc** [comment]
@matthchr, thanks you for sharing your view.
Makes sense.

**Comment by matthchr** [comment]
Closing this as I believe the question is answered.
