### ISSUE TITLE
Unable to install CRD using "make generate"

### ISSUE THREAD

**Issue by abhirockzz** [Azure/azure-service-operator#1821]
**Describe the bug**
Unable to install CRD using "make generate"

**To Reproduce**

- git clone https://github.com/Azure/azure-service-operator/
- opened the project using VS Code (devcontainers) as per - https://github.com/Azure/azure-service-operator/blob/master/hack/CONTRIBUTING.md#developer-setup-with-vs-code
- pointed kubectl to an existing kubernetes (AKS in this case) cluster
- ran `make generate` to install CRD. This failed with the below error:

```
ERROR: unknown flag: --name
cd /tmp/goinstall_Z9BXcpfIbg \
&& go mod init fake/mod \
&& go get github.com/mikefarah/yq/v4 \
&& go get k8s.io/code-generator/cmd/conversion-gen@v0.18.2 \
&& go get sigs.k8s.io/kustomize/kustomize/v3@v3.8.6 \
&& go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.0
go: creating new go.mod: module fake/mod
......
<snip>
......
/go/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
# update manifests to force preserveUnknownFields to false. We can't use controller-gen to set this to false because it has a bug...
# see: https://github.com/kubernetes-sigs/controller-tools/issues/476
# TODO: After this has been in the release for "a while" we can remove it since the default is also false and we just
# TODO: need it for the upgrade scenario between v1beta1 and v1 CRD types
ls config/crd/bases | xargs -I % yq eval -i ".spec.preserveUnknownFields = false" config/crd/bases/%
/go/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths=./api/...

```
**Expected behavior**
Expected `make generate` to install CRD into the k8s cluster configured in `~/.kube/config`

**Screenshots**
NA

**Additional context**
I tried this after facing issue #1820 (couldn't run the operator locally)

**Comment by matthchr** [comment]
There are two major versions of ASO, as called out in our [README](https://github.com/Azure/azure-service-operator#readme). It looks like you got a bit turned around as you were following the ASO v2 [CONTRIBUTING](https://github.com/Azure/azure-service-operator/blob/master/hack/CONTRIBUTING.md#developer-setup-with-vs-code) rather than the document for [ASO v1](https://github.com/Azure/azure-service-operator/blob/master/docs/v1/howto/development.md), but `make generate` is a command that only works/applies to ASO v1.

So the first step in understanding how to help would be: Which version of the operator are you using, and what are you trying to do?

**Comment by abhirockzz** [comment]
I am working on `v2`. The big picture - I am trying to add support for Cosmos DB SQL database resource. See #1780
I made the changes and tried to test the operator locally from with the devcontainer (see #1820), so I thought I might as well try running it against an existing cluster. Looking at the `Makefile`, I thought `make generate` would work just fine.

**Comment by matthchr** [comment]
No, anything to do with the `makefile` is all for `v1`. `v2` build targets are always `task <something>`. For adding Cosmos DB SQL Database in `v2`, were you following the instructions on how to add a [new codegenerated resource](https://github.com/Azure/azure-service-operator/blob/master/docs/v2/adding-new-codegenerated-resource.md)?

There's a section on [writing a CRUD test](https://github.com/Azure/azure-service-operator/blob/master/docs/v2/adding-new-codegenerated-resource.md#write-a-crud-test-for-the-resource) which is the recommended way to test the resource. it doesn't require `kind` or anything.

**Comment by abhirockzz** [comment]
> No, anything to do with the `makefile` is all for `v1`. `v2` build targets are always `task <something>`. For adding Cosmos DB SQL Database in `v2`, were you following the instructions on how to add a [new codegenerated resource](https://github.com/Azure/azure-service-operator/blob/master/docs/v2/adding-new-codegenerated-resource.md)?

Yes, that's right. And that's when I had stumbled upon issue #1780 which was resolved after following your fix.

> 
> There's a section on [writing a CRUD test](https://github.com/Azure/azure-service-operator/blob/master/docs/v2/adding-new-codegenerated-resource.md#write-a-crud-test-for-the-resource) which is the recommended way to test the resource. it doesn't require `kind` or anything.

Isn't there a way to deploy CRD and operator to external k8s cluster using `task` as opposed to `make`? This would be super helpful for sanity testing, before I get into the nitty-gritty of writing tests

**Comment by matthchr** [comment]
> Isn't there a way to deploy CRD and operator to external k8s cluster using task as opposed to make? This would be super helpful for sanity testing, before I get into the nitty-gritty of writing tests

Yeah, it's documented [here](https://github.com/Azure/azure-service-operator/blob/master/hack/CONTRIBUTING.md#running-the-operator-locally), which I think you have already seen. It looks like you've run into some issues with that. You can trying doing the same steps outside of a container possibly? I think you should be able to do that by following the [dev.sh](https://github.com/Azure/azure-service-operator/blob/master/hack/CONTRIBUTING.md#option-2-devsh) instructions?

I'm going to go ahead and close this as the short answer to the question you asked here is that instead of `make generate` you need to run `task controller:install`, which does the same thing as `make generate` but for `v2`. So it really seems like your main issue is what's being discussed in #1820.

**Comment by matthchr** [comment]
Let's move the discussion of the `kind` issue into the other issue you filed.
