### ISSUE TITLE
Feature: Support handcrafted overrides for reconcile

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1978]
This probably needs a basic design as it's involved, but the idea is to support things like:
* Before sending this resource to Azure...
* After this resource has been successfully created...
* After this resource has failed to create...

We also probably need hooks at the ARM serialization/payload level to be able to hook in and deal with inconsistencies, etc.

The general idea here is that we could manually implement an interface on the code generated resource, that lets us craft some specialized handlers to deal with specific cases that aren't possible to handle generically. Things like:
* VNETs PUT deleting its child resources if they aren't present in the PUT.
* Certain resources needing to create a secret by calling a `GetKeys` API or similar.

**Comment by matthchr** [comment]
See #1471 for a feature that will probably make use of this

**Comment by matthchr** [comment]
One thing we're going to need to figure out for this is how it interactions with storage versions. There are sorta two options that I see:

1. Customizations are put on the storage version, this means that the same customization will be run regardless of what API version the customer used.
2. Customizations are put on the customer facing API version. This means that different customizations can be run for the same `Kind` of resource on different API versions but also means that we may need to implement the customization on the storage version (which will then perform the conversion and delegate?) This is a bit awkward though because then we'll run the same conversion twice (we're already doing in inside the storage versions `ConvertToARM`).

**Comment by theunrepentantgeek** [comment]
We need to also think about the upgrading process - if someone injects custom behaviour for version `v2020-06-01` of `microsoft.foobar` then what happens when we introduce support for a later version of that resource, say `v2021-05-01`.

* If the customization is implemented on the API version `v2020-06-01` then it will need to be duplicated on the new version.

* If the customization is implemented on the Hub/Storage version `v2020-06-01-storage` then it will need to be moved/updated as the new version will change the Hub/Storage version to `v2021-05-01-storage`.

Neither approach is entirely simple.

**Comment by matthchr** [comment]
Support for this was added in #2064.
