### ISSUE TITLE
Feature: Support multiple subscriptions resources in the same namespace

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2141]
In a vein similar to the [alternative multitenancy approach](https://github.com/Azure/azure-service-operator/blob/main/docs/v1/design/multitenancy.md#alternatives) we have discussed before, we've had users ask for the ability to manage multiple subscriptions in a single namespace.

One way to do this would be to allow top level resources (ResourceGroups at least, possibly others?) to specify what identity/subscription they are going to use. We might end up with a hierarchy such as:

1. Per top level resource (ResourceGroup) identity and subscription.
2. Per-namespace identity and subscription.
3. Global identity defined in `aso-controller-settings`.

The more specific entry would take precedence over the less specific entry (so per-RG over per-namespace and per-namespace over global). This is similar to what [CAPZ supports](https://capz.sigs.k8s.io/topics/multitenancy.html)

**Comment by max0ne** [comment]
Hey Matthew, thanks for creating this issue.

More details of our usecase:

We have a CRD that defines an "application cluster", this "application cluster" is turned into many other resources by its controller, including an AKS cluster, many other AKS resources like subnet, managed identity, role assignments. Most of these resources live in the same Azure subscription as the AKS cluster, however one role assignment needs to be granted against a different subscription. Our "application cluster" object is namespace scoped, and all the related child resources are also namespace scoped, normally we expect these child resources to be created in the same namespace as their parent "application cluster".

However because a single ASO deployment cannot create objects in multiple subscriptions, we ended up having to create 2 ASO deployments, each wathcing a subscription dedicated namespace. And the ASO child resources are created in those namespaces. Our controller needs to do a mapping from desired subscription to configured namespace.

We have a similar usecase in GKE and when using [GKE Config Connector](https://cloud.google.com/config-connector/docs/how-to/getting-started), where an "application cluster" requires creating resources in multiple GCP projects. In GKE Config Connector, each resource is marked with a project id annotation `cnrm.cloud.google.com/project-id`, this way resources are namespace agnostic, while our controller is able to deploy to any GCP project when needed.
