### ISSUE TITLE
MissingApiVersionParameter error on FlexibleServer

### ISSUE THREAD

**Issue by a1tan** [Azure/azure-service-operator#2372]
ASO V2

**Bug Description**
FlexibleServer dbforpostgresql.azure.com/v1beta20210601 version results with MissingApiVersionParameter error. 

**To Reproduce**
Samples in Github Repository can be used.
https://github.com/Azure/azure-service-operator/tree/main/v2/config/samples/dbforpostgresql

**Azure Service Operator Logs**
I0702 05:16:20.816651       1 azure_generic_arm_reconciler_instance.go:157] controllers/FlexibleServerController "msg"="DetermineCreateOrUpdateAction" "azureName"="samplepostgresql2" "name"="samplepostgresql2" "namespace"="sample-ns" "condition"="Condition [Ready], Status = \"False\", ObservedGeneration = 1, Severity = \"Warning\", Reason = \"InternalServerError\", Message = \"An unexpected error occured while processing the request. Tracking ID: 'f45650cc-3363-41a1-b946-c2b83f1ac85c': GET https://management.azure.com/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/providers/Microsoft.DBforPostgreSQL/locations/westus2/azureAsyncOperation/b8eacc05-4b53-464d-8523-ed54bac49f7a\\n--------------------------------------------------------------------------------\\nRESPONSE 200: 200 OK\\nERROR CODE: InternalServerError\\n--------------------------------------------------------------------------------\\n{\\n  \\\"name\\\": \\\"b8eacc05-4b53-464d-8523-ed54bac49f7a\\\",\\n  \\\"status\\\": \\\"Failed\\\",\\n  \\\"startTime\\\": \\\"2022-07-02T05:15:31.79Z\\\",\\n  \\\"error\\\": {\\n    \\\"code\\\": \\\"InternalServerError\\\",\\n    \\\"message\\\": \\\"An unexpected error occured while processing the request. Tracking ID: 'f45650cc-3363-41a1-b946-c2b83f1ac85c'\\\"\\n  }\\n}\\n--------------------------------------------------------------------------------\\n\", LastTransitionTime = \"2022-07-02 05:15:48 +0000 UTC\"" "pollerID"="" "resumeToken"=""

When I open the link above I face below error.
{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}

**Comment by theunrepentantgeek** [comment]
@a1tan can you please clarify your bug report?

The log snipped above indicates the error "An unexpected error occured while processing the request", which is the error ASO would have received from the PostgreSQL resource provider while tracking the operation `f45650cc-3363-41a1-b946-c2b83f1ac85c`. You likely would be able to diagnose the underlying issue here through the Azure portal. 

Where are you seeing the error "The api-version query parameter (?api-version=) is required for all requests." in the ASO logs?

**Comment by a1tan** [comment]
I have tried again to get detailed errors. Postgresql resource did not come up on azure portal.
The below link from the error logs of ASO shows the specified error "The api-version query parameter (?api-version=) is required for all requests."

https://management.azure.com/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/providers/Microsoft.DBforPostgreSQL/locations/westus2/azureAsyncOperation/b8eacc05-4b53-464d-8523-ed54bac49f7a

This error is also seen as warning level events on kubernetes. 

There is also below error from ASO logs related to this one I guess.
1 controller.go:317] controllers/controller/flexibleserversfirewallrule "msg"="Reconciler error" "error"="Subscription 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' does not have the server ''. Please make sure that the subscription and server name are entered correctly. Please contact Microsoft support if further assistance is needed.: GET https://management.azure.com/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/providers/Microsoft.DBforPostgreSQL/locations/westus2/azureAsyncOperation/fc49b12a-9ad6-49bf-9620-359efe85af53\n--------------------------------------------------------------------------------\nRESPONSE 200: 200 OK\nERROR CODE: SubscriptionDoesNotHaveServer\n--------------------------------------------------------------------------------\n

**Comment by theunrepentantgeek** [comment]
URLs you see in the logs for ASO won't work with a browser - they're the targets of REST API calls to Azure Resource Manager by Azure Service Operator. 

---

Breaking down the log fragment you posted originally, ASO created this long running operation to deploy the PostgreSQL server:

		https://management.azure.com/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/
		providers/Microsoft.DBforPostgreSQL/locations/westus2/azureAsyncOperation/b8eacc05-4b53-464d-8523-ed54bac49f7a

The key piece of information here is the ID of the long running operation, which is the GUID at the end: `b8eacc05-4b53-464d-8523-ed54bac49f7a`

The operation failed, with this error: 
```
An unexpected error occured while processing the request. Tracking ID: f45650cc-3363-41a1-b946-c2b83f1ac85c
```

This is unusual, because it means something went wrong, and the PostgreSQL Resource Provider was unable to provide more details to you. You should be able to see detailed information via the Azure Portal using either the operation id `b8eacc05-4b53-464d-8523-ed54bac49f7a` or the tracking id `f45650cc-3363-41a1-b946-c2b83f1ac85c`.

---

The error you're seeing for `flexibleserversfirewallrule` will be normal; the ASO reconciler loops through trying to reconcile all the resources - in this case, it's unable to create the firewall rule until the server itself exists; once the server does exist, creating of the filewall rule will proceed.

---

A colleague has been working on improving our ASO samples and setting up automated testing (see #2351); I wonder if he's seen any issues with our PostGreSQL samples.

@super-harsh Have you found any issues with the samples for PostgreSQL during your recent testing?

**Comment by theunrepentantgeek** [comment]
@a1tan, we've made some progress. @super-harsh and @matthchr have been doing some testing.

We believe the deployment of the PostgreSQL Flexible Server is failing with an error that we're not surfacing properly through ASO - which means there are two problems:

* Deployment of the PostgreSQL Flexible Server is failing. 
  We're still looking at this.

* ASO not behaving correctly when the deployment fails.  
  @matthchr has identified the problem and has opened PR #2381 with his initial fix.

**Comment by matthchr** [comment]
@a1tan, there were two problems here. One is an ASO bug fixed by #2381, and one is an actual service issue. As @theunrepentantgeek mentioned above, the deployment of the PostgreSQL Flexible Server was actually failing. I _believe_ that this failure has to do with capacity constraints in the region you were attempting to deploy in, but can't be 100% sure. I recommend you raise this issue with the PostgreSQL Flexible Server team via a ticket through the Azure Portal if you're still experiencing this problem.

The _other_ problem is that ASO was not correctly detecting that the creation of the Flexible Server failed and so was trying to GET what it thought was a successfully created server. This kept failing and is the source of most of the errors your saw in the logs. This was our bug which as I mentioned was fixed in #2381 and will be included in the next release, v2.0.0-beta.2.

**Comment by a1tan** [comment]
Thank you for your quick responses and effort @matthchr, @theunrepentantgeek. I will try this after v2.0.0-beta.2 is released. I will let you know if it still continues or not.

**Comment by matthchr** [comment]
If you would like to kick the tires on Flexible Server before beta.2, I would recommend trying a different Azure region to create the Flexible server in. After beta.2, you will see the correct error raised from the service in ASO, but in this particular case since I believe the error is capacity related, you will likely need to use a different region anyway.

During our testing we observed this and I feel pretty confident you were hitting the same thing.

You can also run beta.0 which doesn't have this bug. Only beta.1 has this issue.

**Comment by a1tan** [comment]
Ok, I will try this with a different region. Thanks @matthchr.
