### ISSUE TITLE
Best Practices for Production use of the Operator

### ISSUE THREAD

**Issue by dperaza4dustbit** [Azure/azure-service-operator#2463]
I came across this article which tells me you are designing the operator with production usage in mind: https://devblogs.microsoft.com/cse/2021/11/11/azure-service-operators-a-kubernetes-native-way-of-deploying-azure-resources/

I see one scenario that could be a production use case: Migrating the Application to a new Cluster and bringing existing CRDs over to the new Cluster without affecting the Service underneath. 

In addition to that is there any way to:

1. Rotate credentials
2. Configure DR or BR within the resource representing the service
3. Can I protect for accidental deletion of a CR that represents an important service containing Production Data.

Any other best practices you can share to run the Operator in a production cluster?

**Comment by matthchr** [comment]
> I see one scenario that could be a production use case: Migrating the Application to a new Cluster and bringing existing CRDs over to the new Cluster without affecting the Service underneath.

This is something that you can do, but agree we don't have great documentation describing _how_ to do it. The short answer is that you can just `kubectl apply -f` your resources in another cluster and they'll automatically adopt the existing resources with the same name. A best practice before doing that is to mark the resources in the old cluster with [reconcile-policy: skip](https://azure.github.io/azure-service-operator/introduction/annotations/#serviceoperatorazurecomreconcile-policy) so that the two clusters ASO instances don't fight with one-another on reconciling that resource.

> Rotate credentials

It depends on the specific resource in question. Yes, we support rotating user-supplied credentials (VM password, etc). You do this just by updating the secret you supplied. The operator will pick that change up and perform the update on the backing Azure resource to set the new password/key/etc.

The other kind of secret is an Azure generated secret. These we don't currently support rotating the credentials through ASO (Kubernetes CRDs can't easily model "actions" like `/rotate`, BUT ASO does support working with those resources while their credentials are rotated. For example for an Azure Storage account, you could save the primary and secondary keys into a Kubernetes secret, and then feed those secret values into your running pods as `key1`/`key2` env variables. If you try both keys in your application, you can rotate key1, your application will automatically fall back to using key2. After some time, ASO will realize there is a new key1 and update the corresponding value in the secret, which will percolate down to your application. Then you can rotate key2.

The actual key rotation will need to be done out of band from ASO (for now). You can see the [secrets design](https://azure.github.io/azure-service-operator/design/secrets/) if you're more curious about more details here. Note that that design is a bit more ASO-contributor focused and so we agree with your feedback that we need to improve the user facing documentation to answer this question more clearly.

> Configure DR or BR within the resource representing the service

ASO doesn't do anything special here. If the Azure resource supports DR then you can configure it through ASO. If the underlying Azure Resource doesn't support DR (or the story is more complicated/manual), then you cannot configure it through ASO.

> Can I protect for accidental deletion of a CR that represents an important service containing Production Data.

Yes, in a few ways. 

1. You can set [reconcile-policy: detach-on-delete](https://azure.github.io/azure-service-operator/introduction/annotations/#serviceoperatorazurecomreconcile-policy). This will allow the resource to be deleted in k8s but not delete the underlying resource in Azure.
2. You can use a project like https://github.com/petrkotas/k8s-object-lock to protect the resources you're worried about. Note: That project is not owned/sponsored by MSFT and I don't know how production ready it is.
3. You can manually add a finalizer to the resource which will not be removed except manually by you when ready to delete the resource, see [this](https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/)

There's also a proposal for more general upstream support: https://github.com/kubernetes/kubernetes/issues/10179, although there hasn't been movement on it in quite a long time.

**Comment by matthchr** [comment]
I think I've answered your questions above, but going to leave this issue open for a while to track the following documentation improvements:

1. Document migrating CRs between clusters/namespaces, including best practices like using the `reconcile-policy` annotation
2. Document credential rotation patterns
3. Document preventing a resource from being deleted.

These can be part of an `ASO In production FAQ`, or something like that.

**Comment by dperaza4dustbit** [comment]
Thanks for your answers on this @matthchr looks like is more production ready than I thought for sure. Quick follow questions: 

1. For key rotation looks like an interesting pattern with primary and secondary in place from the beginning, to avoid down time through a rotation. However, the call to rotate will have to be done through Azure APIs it looks like (out of band). When you say "for now" you mean there could be changes in the future to initiate rotation through a state change in the CR representing the service?
2. For DR you say if the Service support DR then you can set that from the CR, that makes sense. But, I was thinking more of a pattern for example where my application is running on two different regions pointing to an already DR enabled cloud service. Let's say I have an app that needs MS SQL and, for DR purposes, I have the app setup as hot/hot on diff region. On region A I set the the ASO resource that describe MS SQL instance. What happens on region B, how do I represent the same cloud service in different k8 clusters?

**Comment by matthchr** [comment]
> When you say "for now" you mean there could be changes in the future to initiate rotation through a state change in the CR representing the service?

Yes, possibly. We don't have any concrete plans here, but we've talked about it for actions other than `/rotate` (for example rebooting VMs, failing over SQL servers). This is something where user feedback is key in my opinion. How painful is it to have to go out of ASO for these sorts of actions?

Do really do a good job on these actions, we'd probably want to fabricate a "Resource" concept that could be used with infrastructure-as-code, rather than just exposing the action as-is through k8s. Think for example if Azure SQL has a `/failover` action. In K8s it makes more sense to instead have a CRD that represents "which server is primary", and then we'd call the `failover` action internally in that based to achieve the goal state if "Server X is primary" when currently "Server Y is primary".

I don't know exactly what the key-rollover equivalent of that pattern would be, but it's possible we come up with one on the future. Not likely to be for a while though.

> Let's say I have an app that needs MS SQL and, for DR purposes, I have the app setup as hot/hot on diff region. On region A I set the the ASO resource that describe MS SQL instance. What happens on region B, how do I represent the same cloud service in different k8 clusters?

Ah, gotcha! This is a pattern we'll definitely need to think about and document more. You _can_ run ASO in active/active in two different regions where each cluster is pointing at the same Azure resources. The main thing you need to make sure in that configuration is that the two operators both have the same goal states, otherwise they will fight with each other. Alternatively you could run in active/passive where the resources in one region are marked [reconcile-policy: skip](https://azure.github.io/azure-service-operator/introduction/annotations/#serviceoperatorazurecomreconcile-policy) and the other region is active. Then if you need to failover you can k apply to remove the `reconcile-policy` annotation and that cluster will start managing those resources.
We don't have a ton of evidence or data about which one of these patterns is better though. Do either of those sound like they would cater to the scenario you're thinking of?

**Comment by dperaza4dustbit** [comment]
Thanks for the response @matthchr it sounds like there is some room for enhancements to improve the production experience. For the DR scenario both patterns sound interesting although only one cluster would need the CR active at a given time so from that point of view active - passive with reconcile-policy: skip should work. However, I could still have a hot - hot from an app point of view as long as the secret representing the service endpoint definition is available in both cluster. This could be done today manually. The problem I see is synchronization. If, secret changes on cluster A due to password rotation, for example, is there a way to make it available on both cluster, without manual step? Similarly, if the CR changes to update the state of the Service. How do I make it available in both cluster?

A related question, if I have the same CR in both clusters today would it be considered an error, like: this Database instance already exists. Or the operator would know is a CR for an existing Service based on a service instance id and no provisioning will be done?

**Comment by matthchr** [comment]
>  The problem I see is synchronization. If, secret changes on cluster A due to password rotation, for example, is there a way to make it available on both cluster, without manual step? Similarly, if the CR changes to update the state of the Service. How do I make it available in both cluster?

Depends a bit on what type of secret you're talking about.

If it's a user-specified secret then you specify it via kubectl apply, so you would just need to automate your secret store to kubectl apply to both clusters as part of your product release/rollout. ASO can't really synchronize this for you because you own the lifecycle of the secret, but since its your app across N clusters you can just do the same kubectl apply's across all the clusters.

If it's an Azure generated secret that you've rolled over manually out of band, ASO will notice it even if reconcile-policy is `skip`. Right now by default ASO re-reconciles resources every ~15m, which means it will take at most 15m for the operator in either cluster to pick up the new credentials. There's room for improvement here though obviously, and if we did have some sort of way to know you've done a secret rollover out of band we could trigger an event to make that update immediate, which would be great.

> A related question, if I have the same CR in both clusters today would it be considered an error, like: this Database instance already exists. Or the operator would know is a CR for an existing Service based on a service instance id and no provisioning will be done?

It's not an error. Assuming no annotations on either cluster, both clusters will attempt to own the 1 underlying Azure resource. This is fine as long as the desired goal state in both clusters is the same. If it's not the same, the operators will fight (which is bad). That's why we recommend only having one active operator owning the resource at any given time, and using something like `reconcile-policy` to have the other operators watching in a passive state, but not making any changes. You can read some more about design thoughts we have on this here #2067.
