### ISSUE TITLE
Questions about mandatory role scope for ASO service principal

### ISSUE THREAD

**Issue by germaino** [Azure/azure-service-operator#2507]
Hello,

In the ASO documentation it is mentioned that the ASO service principal or managed identity need to have "Contributor permissions for your subscription".
Is is possible to have a lower permission scope at one more resource groups instead ?
Thanks for your feedback
Regards
Olivier

**Comment by germaino** [comment]
Clear, thanks for the explanation. I guess this works for both SP and managed identity ? 
Is it possible to give ASO contributor permissions on different resource groups and have the resource created on the right resource group based on the owner name (spec field).
Yes, correct I saw that in the step2 [installation](https://azure.github.io/azure-service-operator/#installationrl)

**Comment by matthchr** [comment]
> I guess this works for both SP and managed identity ?

Yes.

> Is it possible to give ASO contributor permissions on different resource groups and have the resource created on the right resource group based on the owner name (spec field).

Yes, this is how I would expect you to do it. So for example say you want to manage 5 resource groups with ASO. You've precreated the RGs, created an identity for ASO (either SP or MI, doesn't matter), given that identity contributor access to those 5 RGs, and installed ASO using that identity..

Now you can either have ASO take ownership of the existing RGs, or just import them into k8s (for user as `owner` refs but not actually actively reconciling the RGs). See #2067 and [reconcile-policy](https://azure.github.io/azure-service-operator/introduction/annotations/#serviceoperatorazurecomreconcile-policy). You'd use `skip` to adopt and not manage, or no annotation (default) to adopt and manage.

Now that the 5 RGs exist in your cluster, you can make resources inside of them by `kubectl apply`-ing whatever stuff you want to make. As long as the owner of the resources you are creating points to one of the 5 RGs you've got (via `spec.owner`)*, everything works great. If somebody tries to create a 6th RG, that error I mentioned above will appear as ASO doesn't have permission to do that with the identity it is running as.

*Note they don't have to point directly to the RG. If you have a hierarchy like this for example it all still works fine: RG -> StorageAccount -> Container. The container `spec.owner` will point to the storageaccount, not to the RG, but that's ok because the storage account itself has its `spec.owner` as the RG.

**Comment by germaino** [comment]
Yes, perfect, thanks a lot !
