### ISSUE TITLE
User Managed Identity or System Managed Identity?

### ISSUE THREAD

**Issue by mickledur** [Azure/azure-service-operator#2624]
**Describe the current behavior**
We deployed Azure Service Operator v2.0.0-beta.0 and for the deployment we are using Azure User assigned Managed Identity to authenticate ASO. The deployment is working as expected. Our concern is about security and the fact that User assigned Managed Identity can be assigned to multiple Azure Resources and we cannot guarantee that only ASO is using this identity 
We were wondering if it would be better, speaking of security, that we use System assigned Managed Identity since this kind of Managed Identity can only be assigned to one resource and will be deleted when resource is deleted.
**Describe the improvement**
Is it recommended to use System Assigned Identity rather than Managed Identity?

**Additional context**
Version: v2.0.0-beta.0

Thanks for your support

**Comment by theunrepentantgeek** [comment]
We don't take a position on whether it's universally better to deploy ASO using a user-assigned or system-assigned managed identity because the correct choice for you depends on your own context.

If you haven't already read it, we have a good [best practices for managed identity](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/managed-identity-best-practice-recommendations) guide that may be useful.
