### ISSUE TITLE
Service Bus: Primary Key Secret

### ISSUE THREAD

**Issue by hannah38** [Azure/azure-service-operator#2708]
**Describe the current behavior**
Currently, only `endpoint` exposed as a secret for Service Bus https://github.com/Azure/azure-service-operator/blob/faaba108c934887c8ff9ca3dd61e668878818d5a/v2/api/servicebus/v1beta20210101preview/structure.txt#L27

**Describe the improvement**
I want to ask if primary key will also be exposed as a secret for Service Bus

**Additional context**
Previously we used OSBA which provided primaryKey https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/servicebus.md#credentials, so our applications are currently set up to use this.

**Comment by thomast1906** [comment]
+1 requirement for this; this current setup works fine for Storage Accounts - wondering can same functionality be added to Service Bus as mentioned above?

**Comment by theunrepentantgeek** [comment]
The documentation for Service bus [says](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-authentication-and-authorization#azure-active-directory):
> Authorizing users or applications using OAuth 2.0 token returned by Azure AD provides superior security and ease of use over shared access signatures (SAS). ... We recommend that you use Azure AD with your Azure Service Bus applications when possible.

Because of this, we've so far held off on implementing support for SAS keys.

ASO supports creating [new managed identities ](https://azure.github.io/azure-service-operator/reference/#managedidentity)  and [assigning permissions ](https://azure.github.io/azure-service-operator/reference/#authorization). You would then use [Azure workload identity](https://github.com/Azure/azure-workload-identity) to assign that identity to your application pods and authenticate with Service Bus

That said, if you can't use managed identity, we are willing to add support to expose both primary and secondary keys as you've requested.

Let us know if you'd like this added to our roadmap for v2.1.0. 

One last thought: We'd accept a PR if you want to have a go at implementation yourself. If you want to go this route, we can give you some pointers on what's needed.

**Comment by hannah38** [comment]
Hi, thanks for your reply. I'd like to follow up on your last thought about creating a PR myself for this if you'd be able to provide those pointers.

**Comment by theunrepentantgeek** [comment]
Awesome! Off the top of my head ...

* Modify `v2/azure-arm.yaml` to add both `PrimaryKey` and `SecondaryKey` as exported secrets.
* Build and run the generator to update the generated code (running `task` in the root folder of the repo should do this)
* Modify the code in `v2\api\servicebus\customizations\namespace_extensions.go` to retrieve and add the new secrets
* Add a new test to `v2\internal\controllers\crd_servicebus_namespace_standard_test.go` that retrieves both keys and checks they're present after reconciliation completes

Our docs on [Contributing to ASO](https://azure.github.io/azure-service-operator/contributing/) should be helpful (and if they're not, let us know so we can improve them!).

Feel free to post any questions you have here, or if you prefer, you could also use the [azure-service-operator](https://kubernetes.slack.com/archives/C046DEVLAQM) channel over on the Kubernetes Slack.

**Comment by theunrepentantgeek** [comment]
I hope it doesn't bother you @hannah38 - I've implemented this.

**Comment by theunrepentantgeek** [comment]
@hannah38, further to my above comment, there's a special admin level `AuthorizationRule` that's created automatically; I've exposed the secrets from that as secrets on the `Namespace` itself, mirroring the OSBA experience.

This will be included in the upcoming v2.1.0 release.
