### ISSUE TITLE
Explicitly list our dependencies

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3047]
**Describe the current behavior/improvement**

As identified by @super-harsh in PR #3041, it would be helpful for users who don't want to rely on `install-dependencies.sh` to have a canonical list of things they should install manually in order to do ASO development.

**Comment by matthchr** [comment]
I'm not sold that we need anything other than `install-dependencies`. The canonical list is: "read the script and install those dependencies manually"?

As long as the script is relatively readable, the code being the documentation seems best to me. Otherwise it's just inevitably going to get out of date.

**Comment by theunrepentantgeek** [comment]
That's a good suggestion - a bit of work to make the script as readable as possible may well be sufficient.

**Comment by super-harsh** [comment]
We can consider having a `-l` / `--list` option in the script, which dynamically goes through the script and lists dependencies. Similar to how `--dry-run` works.
