### ISSUE TITLE
Feature: Manage App Service resources

### ISSUE THREAD

**Issue by cdc1807** [Azure/azure-service-operator#3051]
Would like to request adding support for [App Service](https://azure.microsoft.com/en-us/products/app-service). 

I see the Azure SDK already has the [ARM mapping](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/appservice/armappservice) but ASO is currently running `v57.2.0` (at this time this issue was created) which does not have this. Is there a plan to upgrade to a newer, refactored version of the SDK? I didn't see any related issues to this upgrade.

**Comment by theunrepentantgeek** [comment]
Which additional Azure resources do you want ASO to support?

In [this example](https://learn.microsoft.com/en-us/azure/app-service/provision-resource-bicep), there are three resource types included:

* Microsoft.Web/serverfarms
* Microsoft.Web/sites
* Microsoft.Web/sites/sourcecontrols

We [already support](https://azure.github.io/azure-service-operator/reference/web/) the first two, and can investigate the third if this is what you want.

_Aside_: ASO uses the ARM API to create & maintain resources, not the Azure Go SDK. We use the later for a small number of operations not directly supported by ARM.

**Comment by cdc1807** [comment]
Thanks for the quick reply and insights. Wasn't aware of some of the naming differences. Those first 2 resources appear to support everything needed.

> Aside: ASO uses the ARM API to create & maintain resources, not the Azure Go SDK. We use the later for a small number of operations not directly supported by ARM.

Can you please point me to an example of this? Still learning Azure, but clicking through a number of resources in ASO and all the clients I'm seeing utilize `github.com/Azure/azure-sdk-for-go/services`.  Maybe just bad luck on my part or I'm not understanding the difference between the SDK and ARM API usage. The other Azure package in `go.mod` is `github.com/Azure/go-autorest`which seems more like a utility.

**Comment by matthchr** [comment]
@cdc1807 - I believe you are looking at ASOv1, and @theunrepentantgeek is talking about ASOv2.

The ASOv2 code is here: https://github.com/Azure/azure-service-operator/tree/main/v2. You can see examples for how to use the resources in question here: https://github.com/Azure/azure-service-operator/tree/main/v2/samples/web/v1api

For installing ASOv2, look at: https://azure.github.io/azure-service-operator/#installation

**Comment by matthchr** [comment]
If you're satisfied with the above response please let us know and we can close this issue. Thanks!

**Comment by cdc1807** [comment]
@matthchr The issue can be closed. I think you were kinda right in that I was unknowingly looking at v1 but even looking at the [v2 go.mod](https://github.com/Azure/azure-service-operator/blob/main/v2/go.mod) it still is referencing the SDK and no other Azure resources.

**Comment by cdc1807** [comment]
I was looking at the imports to try and better understand the ARM API and how it's being leveraged by the controller. Original assumption was it would be another go module itself but I'll keep browsing. Don't actually need it for anything, just got curious.

Like all controllers/operators the `api` directory is the best starting point (looking solely at the code) when wanting to know list of types. But yes the docs certainly make it easier.

**Comment by matthchr** [comment]
Yeah, `api` is the best starting point. You'll see code-generated `_ARM` types there, that's basically our "sdk"

We don't actually rely on the SDK we basically code-generate an SDK for ourselves and use the Go SDK core to produce ARM JSON payloads. The reason for that is:
1. The Go SDK always tracks the latest API version but for stability reasons we wanted to be able to target older REST API versions too.
2. We're already code-generating the Kubernetes resources, so in some ways it's easier for us to code-generate the ARM resources too so we can easily define property mappings between the two types - rather than _assuming_ the mappings will be there in the Go SDK and then getting surprised when the shape of the SDK doesn't match the expected ARM shape.

For those reasons and a few much more subtle ones, we don't use the SDKs for main PUT/GET/DELETE patterns. As I mentioned above sometimes we do include the SDK for some other operations it offers, or to call in our tests.

Going ahead and closing this as I think your core questions were answered.
