### ISSUE TITLE
Bug: VNET and Subnet created in ASO adopting existing VNET/Subnet will always delete the subnets and recreate them

### ISSUE THREAD

**Issue by pb-adrianbezzina** [Azure/azure-service-operator#3077]
ASO V2: 

```azureserviceoperator-controller-manager   1/1     1            1           40m   manager,kube-rbac-proxy   mcr.microsoft.com/k8s/azureserviceoperator:v2.1.0,gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1   control-plane=controller-manager```

**Describe the bug**
Create a VNET with ASOV2, added subnets and configured AKS in those subnets - this is done via a locally running Kind instance running on my laptop.

Kind was then destroyed and recreated and the manifests reapplied - all resources reconciled healthy except the VNET (and subsequent children resource dependent on the VNET)

Now it complains with the following error:

```
Subnet podsubnet is in use by /subscriptions/28848791-fcd6-43a7-aeef-767b1a66fede/resourceGroups/rg-vnet-ab-devtest/providers/Microsoft.Network/virtualNetworks/vnet/subnets/podsubnet/serviceAssociationLinks/AzureKubernetesService and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.: PUT https://management.azure.com/subscriptions/28848791-fcd6-43a7-aeef-767b1a66fede/resourceGroups/rg-vnet-ab-devtest/providers/Microsoft.Network/virtualNetworks/vnet -------------------------------------------------------------------------------- RESPONSE 400: 400 ERROR CODE: InUseSubnetCannotBeDeleted -------------------------------------------------------------------------------- { "error": { "code": "InUseSubnetCannotBeDeleted", "message": "Subnet podsubnet is in use by /subscriptions/28848791-fcd6-43a7-aeef-767b1a66fede/resourceGroups/rg-vnet-ab-devtest/providers/Microsoft.Network/virtualNetworks/vnet/subnets/podsubnet/serviceAssociationLinks/AzureKubernetesService and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.", "details": [] } } --------------------------------------------------------------------------------
```

**Expected behavior**
VNET should not be complaining about subnets being used based on this bug fix: #2169

**Comment by matthchr** [comment]
Can you share the ASO logs from the `manager` container in the operator pod?

Specifically, when the VNET was created I think there should be a log like this:
`log.V(Info).Info("Found subnets to include on VNET", "count", len(armSubnets), "names", genruntime.ARMSpecNames(armSubnets))`

I want to see what it logged.

**Comment by matthchr** [comment]
Ah, I think I see the problem. Here's the sequence of events:

1. VNET is created (first `kind` iteration)
2. Subnet is created (first `kind` iteration).
3. Subnet has additional data added (`serviceAssociationLinks`)
4. `kind` cluster is deleted
5. VNET + Subnet is reapplied

In step 5 when the VNET is recreated, it queries for all the subnets that it owns in [virtual_network_extensions.go](https://github.com/Azure/azure-service-operator/blob/main/v2/api/network/customizations/virtual_network_extensions.go#L51). Specifically, ownership is determined by:
```
	matchingFields := client.MatchingFields{".metadata.ownerReferences[0]": string(obj.GetUID())}
	err := kubeClient.List(ctx, subnets, matchingFields)
```

This is a problem though because when the vnet + subnets are recreated, the subnets aren't _actually_ marked as owned by the VNET until the VNET is successfully created. See the code that does that [here](https://github.com/Azure/azure-service-operator/blob/main/v2/internal/reconcilers/common.go#L101)

This causes the VNET to be first created without any subnets specified. Doing this attempts to delete all of the subnets (they will immediately be recreated).

There are two possible fixes that I see:
1. Update [ClaimResource]([here](https://github.com/Azure/azure-service-operator/blob/main/v2/internal/reconcilers/common.go#L123) to `ApplyOwnership` always, regardless of if the owner has been created yet in Azure or not. This is safe because deletion of resources that don't yet exist is a no-op anyway. This may not completely fix the issue as there might still be a race between reconciliation of the VNET and reconciliation of the subnets.
2. Update the [virtual_network_extensions.go](https://github.com/Azure/azure-service-operator/blob/main/v2/api/network/customizations/virtual_network_extensions.go#L51) and other similar extensions such as for LoadBalancer to not rely on `ownerReferences` and instead determine all of the owned subnets by the `.spec.owner` field.

I think solution 2 should be preferred.

**Comment by matthchr** [comment]
Note that this bug actually applies to every networking resource we have which has this pattern (There are a few others in addition to VNET such as LoadBalancer)
