### ISSUE TITLE
why this happens when I use asoctl, and kubectl apply, it shows below

### ISSUE THREAD

**Issue by mingmingshiliyu** [Azure/azure-service-operator#3270]
``` shell
wtst45x@MacBook-Pro additional % kubectl apply -f resources.yaml                                                            
Error from server (Invalid): error when creating "resources.yaml": ManagedCluster.containerservice.azure.com "testcluster" is invalid: spec.owner: Required value
Error from server (Invalid): error when creating "resources.yaml": ManagedClustersAgentPool.containerservice.azure.com "testcluster-agentpool" is invalid: spec.type: Unsupported value: "Microsoft.ContainerService/managedClusters/agentPools": supported values: "AvailabilitySet", "VirtualMachineScaleSets"
Error from server (Invalid): error when creating "resources.yaml": ManagedClustersAgentPool.containerservice.azure.com "testcluster-userpool" is invalid: spec.type: Unsupported value: "Microsoft.ContainerService/managedClusters/agentPools": supported values: "AvailabilitySet", "VirtualMachineScaleSets"
```

**Comment by mingmingshiliyu** [comment]
so confused! new in azure, how can I resolve it

**Comment by theunrepentantgeek** [comment]
These are errors coming from your cluster because your `resources.yaml` file has issues - you'll need to fix those in order for `kubectl` to work.

Since you haven't shared `resources.yaml`, I can't do much to assist, but here are some pointers.

```
ManagedCluster.containerservice.azure.com "testcluster" is invalid: spec.owner: Required value
```

You haven't provided a value for the `owner` property with the `spec` of your `ManagedCluster` definition. From the [`ManagedCluster`](https://azure.github.io/azure-service-operator/reference/containerservice/v1api20230201/#containerservice.azure.com/v1api20230201.ManagedCluster) documentation, we see that `owner` is a reference to the owner of the cluster. 

Populate this with a reference to the Azure ResourceGroup into which the cluster should be created.

```
ManagedClustersAgentPool.containerservice.azure.com "testcluster-agentpool" is invalid: spec.type: 
Unsupported value: "Microsoft.ContainerService/managedClusters/agentPools": 
supported values: "AvailabilitySet", "VirtualMachineScaleSets"`
```

For the `type` of your AgentPool, you need to specify either `AvailablilitySet` or `VirtualMachineScaleSets` (see [documentation](https://azure.github.io/azure-service-operator/reference/containerservice/v1api20230201/#containerservice.azure.com/v1api20230201.AgentPoolType)). 

The `Microsoft.ContainerService/managedClusters/agentPools` you provided is the type of the Custom Resource from a Kubernetes perspective and doesn't belong within the `spec`. It should be set on the `apiVersion` line of your file.

```
ManagedClustersAgentPool.containerservice.azure.com "testcluster-userpool" is invalid: spec.type: 
Unsupported value: "Microsoft.ContainerService/managedClusters/agentPools": 
supported values: "AvailabilitySet", "VirtualMachineScaleSets"
```

This is the same problem, on your other agent pool.

**Comment by theunrepentantgeek** [comment]
Have a look at the samples we have for [ManagedCluster](https://github.com/Azure/azure-service-operator/blob/main/v2/samples/containerservice/v1api20230201/v1api20230201_managedcluster.yaml) and [AgentPool](https://github.com/Azure/azure-service-operator/blob/main/v2/samples/containerservice/v1api20230201/v1api20230201_managedclustersagentpool.yaml), these show simple configurations that may be a useful reference.

**Comment by theunrepentantgeek** [comment]
No update from user, closing.

**Comment by arsdragonfly** [comment]
@theunrepentantgeek still an issue for latest `asoctl` in that it won't populate `owner` field of `spec` when `import`ing a `ManagedCluster` `azure-resource`.
