### ISSUE TITLE
Bug: Crash when specifying a single namespace for AZURE_TARGET_NAMESPACES

### ISSUE THREAD

**Issue by bmwinstead** [Azure/azure-service-operator#3300]
**Version of Azure Service Operator**

2.3.0

**Describe the bug**

Specifying a single namespace in `AZURE_TARGET_NAMESPACES` causes ASO to CrashLoopBackOff with the following log message:
```bash
❯ kubectl logs azureserviceoperator-controller-manager-7f4db8b7c-sh8jp
I0914 15:36:59.861906       1 main.go:29] setup "msg"="Launching with flags" "flags"="MetricsAddr: 0.0.0.0:8080, HealthAddr: :8081, EnableLeaderElection: true, CRDPatterns: , PreUpgradeCheck: false"
E0914 15:36:59.920709       1 setup.go:129] setup "msg"="unable to create manager" "error"="must specify more than one namespace to use multi-namespace cache"
```

**To Reproduce**

1. Specify a single value for `AZURE_TARGET_NAMESPACES` 
2. Watch it crash

**Expected behavior**
Not crash

**Screenshots**
N/A

**Additional context**
values used during install:
```
❯ helm get values aso
USER-SUPPLIED VALUES:
azureClientId: {real value}
azureOperatorMode: watchers
azureSubscriptionId: {real value}
azureTargetNamespaces: testns
azureTenantId: {real value}
createAzureOperatorSecret: true
multitenant:
  enable: true
useWorkloadIdentityAuth: true
```

**Comment by matthchr** [comment]
Good catch. This looks related to the upgrade of controller-runtime we did.

Here's the code [from before](https://github.com/kubernetes-sigs/controller-runtime/blame/fbaf768d018bee9a6ae7c1d90559689ef2ce93a0/pkg/cache/multi_namespace_cache.go).

Here's the [code as of 0.15](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.15.0/pkg/cache/multi_namespace_cache.go#L53)

and here's the [code as of 0.16](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.16.0/pkg/cache/multi_namespace_cache.go#L46)

So I _think_ that this problem was introduced in 0.15 and then removed in 0.16...

**Comment by matthchr** [comment]
FWIW I think you could work around this issue now by specifying a dummy namespace (a GUID?) in addition to the single namespace you want to watch.
