### ISSUE TITLE
Document secrets required to run CI

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3323]
**Describe the current behavior**

Our CI builds depend on having eight secrets defined, but we have no documentation on what each secret means (other than the somewhat opaque names), and how to rotate the values. 

I suspect this information is currently tied up as oral tradition, but we should capture those details so that we're not reliant on someone's brain to know how to configure CI. 

**Describe the improvement**

Document all four values, including the process of updating the values and how to generate the required credentials.

**Additional context**

Must include details about required permissions, troubleshooting etc.

**Comment by matthchr** [comment]
Given this is likely going to change due to #https://github.com/Azure/azure-service-operator/issues/3930, and is already somewhat documented at https://azure.github.io/azure-service-operator/contributing/testing/, I propose we hold off on doing anything on this item until after #3930, and moving this to 2.8.0.

**Comment by matthchr** [comment]
There are now no separate credentials, only the az-login token which is used to make (temporary) credentials at whatever other scopes we need, so I think that the documentation at https://azure.github.io/azure-service-operator/contributing/testing/ is now sufficient.

**Comment by theunrepentantgeek** [comment]
There are other secrets to document.
