### ISSUE TITLE
Bug: Resource doesn't re-reconcile after completed update

### ISSUE THREAD

**Issue by nojnhuh** [Azure/azure-service-operator#3451]
**Version of Azure Service Operator**

v2.3.0

**Describe the bug**
After making a change to the `spec` of a resource while that resource is already being updated, the new change does not apply until after the next periodic resync.

**To Reproduce**
(This is the particular case I was hitting, not exactly sure how general this applies.)
- Create a ManagedClustersAgentPool with `spec.orchestratorVersion = 1.27.1` and `spec.count = 1`
- Update `spec.orchestratorVersion` to `1.27.3`
- While the upgrade is happening, update `spec.count` to 2
- After the upgrade finishes, `status.orchestratorVersion` is `1.27.3` as expected, but `status.count` is stuck at 1 and there are no signs of a scaling event occurring in the portal until ASO's next periodic resync.

**Expected behavior**
A scaling operation begins shortly after the Kubernetes version upgrade completes.

**Screenshots**

**Additional context**

**Comment by matthchr** [comment]
Reproducing from the slack convo for the record:

The problem is that if there's an active pending reconciliation event then a new event just gets subsumed into that one. The events are just prio-queue entries, I think. So when a reconciliation is ongoing and a change happens, we think we've applied both when we really havent. Probably what we ought to do is hash the spec each time we apply, and when we finish an apply check that the spec we have now actually has been applied and if not, queue again.
