### ISSUE TITLE
Bug: RoleAssignment UUID clashes

### ISSUE THREAD

**Issue by Roman-Galeev** [Azure/azure-service-operator#3637]
**Version of Azure Service Operator**
v2.4.0

**Describe the bug**
We have development, staging and production subscriptions for deployments, and each of them has a managed kubernetes service (AKS), so the algorithm used to calculate "stable" AzureName UUID produces clashes. This is the function used currently:

```
		assignment.Spec.AzureName = randextensions.MakeUUIDName(
			ownerGK,
			assignment.Spec.Owner.Name,
			gk,
			assignment.Namespace,
			assignment.Name)
```

I believe that "uniqueness" of the UUID could be easily improved by including into the seed string subscription ID (which is known to ASO anyways). However, this will not cover the case when there are more than one cluster in the subcription, but handling that is a more complex story, e.g. ASO could generate an instance ID on install, and use it as a seed.

**Comment by matthchr** [comment]
> I'm open to moving to include subscription in this too, although we'd need to think about how to do so in a way which is backwards compatible as we won't want to orphan existing RoleAssignments.

Actually we wouldn't break existing RoleAssignments because defaulting only applies when they create a new one, it would break the case where they move RoleAssignments between two instances of ASO w/ the same name. Possibly we could document our way around that.

A (likely bigger) problem is that, at the point the webhook runs we don't actually know the subscription and it's actually possible that the subscription configuration doesn't exist yet, so it might be difficult for the webhook to take it into account.

Have you considered just using something like `kustomize` to make your dev/test/prod env roleassignments have slightly different names?

`-dev`, `-test` and `-prod` suffix on the RoleAssignment would solve the problem without you needing to fully manage the UUID yourselves.

**Comment by Roman-Galeev** [comment]
...and another idea is including principalID into role UUID seed, instead of owner.

related: https://github.com/Azure/azure-service-operator/issues/3318

**Comment by theunrepentantgeek** [comment]
There's an interesting conflict here between the two scenarios. In one case, generating a stable UUID for the role identity is crucial to allowing resources to be handed off between ASO instances; in the other, having a different UUID for each installation is needed to keep dev/test/prod environments separate.

I suspect there's no one-size-fits-all solution here; maybe we need to add some configuration to `RoleAssignment` to control how the stable UUIDs are generated. I'll drop this issue into our next milestone and tag as `high-priority` so we don't lose sight of it.
