### ISSUE TITLE
Guidance on release process

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-service-operator#3648]
Are there plans to document the release schedule to help set expectations?

THings thinking of:
- How often do you ship?
- Are there nightly builds we can use for testing?

**Comment by theunrepentantgeek** [comment]
Documenting how we manage the roadmap is a good idea, we'll do that. 

What we've been doing is a release approximately every two months (v2.5.0 was an exception that we completed early, prior to the end of year holiday season). I'd expect us to continue that cadence in 2024.

We haven't been publishing nightly builds, we'll discuss that. 

Leaving `needs-triage` so that we discuss this when we resume our weekly sync in the new year.

**Comment by tomkerkhove** [comment]
This is how we do it on the KEDA side: https://github.com/kedacore/keda/blob/main/ROADMAP.md#upcoming-release-cycles

**Comment by tomkerkhove** [comment]
Thank you!
