### ISSUE TITLE
Provide capability to build experimental image from non-main branch

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-service-operator#3713]
**Describe the current behavior**
https://github.com/Azure/azure-service-operator/pull/3699 introduces the capability to build experimental images from main branch for every push to it.

**Describe the improvement**
Provide capability to build experimental image from non-main branch

**Additional context**
Follow-up after https://github.com/Azure/azure-service-operator/issues/3682

**Comment by tomkerkhove** [comment]
Feel free to assign to me

**Comment by matthchr** [comment]
I've assigned this to you @tomkerkhove.

I'm not 100% sold it makes sense for us to have GH actions for this - it's already possible to test non-main branches locally by using the corresponding `task` targets, and you can build and push images as well (there are taskfile targets for that as well as provisioning an AKS cluster and launching the local copy of the operator there, or in `kind` - both are supported).

They may need to be better documented though, so that users who want to do this know how to do so without reading through the Taskfile.

Reason I say this is that I'm not sure we want to host the images in our official ACR like we do for releases and `experimental`.

**Comment by tomkerkhove** [comment]
I think the reasoning for this is primarily to _not_ ask people to go through all of that and if there is a customer that has to validate an issue we can give them the artifacts instead.

However, I get that this might be too much now that we have main images so maybe this is something we should have ourselves on the APIM side (which I have actually just set up)

**Comment by tomkerkhove** [comment]
@matthchr is this something you are still considering or decided not to do (which would be ok)?

**Comment by tomkerkhove** [comment]
That makes sense.

We actually have this available in our fork, so if you are open to it I can just contribute it.

**Comment by matthchr** [comment]
Do you have a link to how you have it set up in the fork? Let me sync w/ @theunrepentantgeek and check out how you've done it in the fork first?

**Comment by tomkerkhove** [comment]
It is just as simple as this - https://github.com/ansulgoenka/azure-service-operator/blob/main/.github/workflows/create-release-experimental.yml

But it should likely be improved to not update the existing `experimental` tag and instead do it with `experimental-<branch>` to not mess up the "official previews"

**Comment by matthchr** [comment]
@theunrepentantgeek and I synced on this and decided for now it makes sense to avoid accepting changes for this just let you manage it in your fork. Sorry for the flip-flopping!

I'm going to go ahead and close this.
