### ISSUE TITLE
Provide way to fill out crdpattern in raw release YAML

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#3719]
**Describe the current behavior**
crdpattern is empty so the pod won't come up cleanly

**Describe the improvement**
crdpattern should be specified, at least for the experimental release. Possibly for all releases (though that begs the question what to default it to...), OR there should be some way for users to supply it if it's not going to be defaulted.

**Comment by tomkerkhove** [comment]
If you share what exactly needs to be done, then I'm happy to open a PR

**Comment by theunrepentantgeek** [comment]
When we made the decision to introduce `crdPattern` we considered doing this and decided against - because we couldn't identify a reasonable default that wouldn't result in nasty surprises for users.

* If we specify a subset of available resources, then anyone wanting to try out ASO with a different resource would naturally conclude _"This piece of excrement doesn't work."_ when their attempt to create the CR fails.
* If we specify `*` then anyone trying it out on a free tier AKS cluster (which is the obvious choice) will find the pod constantly restarts, and would naturally conclude _"This piece of excrement doesn't work."_

We decided a missing mandatory field with an up-front error at least forces the issue in front of people and they know what's going on.

So, my question is this: what's new? Happy to relitigate this decision if we have new information ... but if we don't, we should let the existing decision stand.

**Comment by matthchr** [comment]
The user experience for this field not being set isn't great. It just means that the pod doesn't come up. Users need to go look at the pod logs to see what the problem is, which sucks.

In the standard installation experience, that's not _so much_ of an issue because the default/recommended installation pattern is to use Helm, where `crdPattern` is a parameter that can easily be set. Even with Helm we hadn't been _requiring_ that parameter be supplied, I've just sent (#3749). The point though is that since Helm is a templating language there's a way to require this parameter and allow the user to easily specify it.

For installing the raw YAMLs, there's no built in templatization which means that there's no way for the user to install the YAMLs and have them work. https://azure.github.io/azure-service-operator/guide/installing-from-yaml/ doesn't even mention `crdPattern`, which is (IMO) an oversight - I've added to our docs issue tracking that, we should fix it. Users that use the raw YAMLs need to download and manually modify the YAML to supply a crdPattern value, _or_ modify the deployment in their cluster once the initial deployment creation fails as the pod doesn't start.

> because we couldn't identify a reasonable default that wouldn't result in nasty surprises for users.

I think this is still true but especially with the experimental releases, where this is no Helm alternative, the user experience is bad. We need to think of a way to have our cake and eat it too here, not defaulting to a wrong choice, but also not making it very difficult to specify the option you want to pick.

**Comment by matthchr** [comment]
We probably need to do a small design document that outlines the different options here as there are quite a few we could pursue.

**Comment by matthchr** [comment]
Thinking we can just discuss the options here at least to start. Here are the ones I see:

**Leave it as-is**

Obviously this is pretty awkward. Not recommended.

**Use envsubst**

This basically just involves setting this as an env variable in the file and then updating our documentation to use `envsubst`.

Pros:
- Simple

Cons:
- Only works on Linux, Windows substitution would be different and likely use a different tool.
- The variable still isn't really required, user won't get a clear error if they don't set the right var they'll still need to look at pod logs.

**Use kustomize**

Pros:
- Built into kubectl, cross platform

Cons:
- Still no notion of "required" variables but we could have a few presets like `rg-only`, `all` and a few others and then users would download the folders and could edit the overlay to set whatever they want.

**Use new asoctl cmd**

Pros:
- Cross platform
- Could make the parameter required in a way not supported by Kustomize or envsubst.

Cons:
- Not built into kubectl

In terms of what other projects do:
- CAPI uses `clusterctl` which is obviously similar to `asoctl`, you can see here: https://cluster-api.sigs.k8s.io/user/quick-start.html
- cert-manager supports raw [YAML and Helm (as well as operatorhub)](https://cert-manager.io/docs/installation/#default-static-install)
- KEDA supports [YAML, Helm, and Operator Hub](https://keda.sh/docs/2.13/deploy/)
- Jaeger supports [Raw YAML](https://www.jaegertracing.io/docs/1.56/operator/#installing-the-operator-on-kubernetes)
- Rook uses [various raw YAMLs](https://github.com/rook/rook/blob/release-1.14/Documentation/Getting-Started/example-configurations.md)

Given the combinatorial nature of Azure resources (no two users will use the exact same set), I don't think what some of these projects do with various YAMLs pre-fabricated will work for us. I tend to lean in the direction of an `asoctl` command.

Something like:
```
$ asoctl install operator --help
Installs the ASO operator

Usage:
  asoctl install operator [flags]

Flags:
  -h, --help                   help for install
  -n, --namespace string       Install the operator into the specified namespace.
  -v, --version                The version of the operator to install, if not specified the default is the latest stable version.
      --crdPattern             The CRD pattern to use

Flags:
      --dry-run   
  -h, --help      help for clean

Global Flags:
      --verbose   Enable verbose logging
```

**Comment by jackfrancis** [comment]
@matthchr why doesn't the pod come up cleanly if --crd-pattern is empty?

**Comment by matthchr** [comment]
The pod doesn't come up cleanly if there are no CRDs installed. We specifically exit with a nonzero code, thinking is that ASO operator + no CRDs is probably unintended from the user and the pod cycling means it's more obvious than it would otherwise be.

Even if the pod came up though, we still want the user to select what CRDs they want and we recommend using the `crdPattern` to control which are installed (means upgrades are managed correctly, etc), so we really want the user to set that field just from a best practices perspective regardless, whihc means the fact they _cant_ in the raw YAML installation right now is awkward.

I guess another option that I missed above was, raw yaml _doesnt_ use crdpattern and the user can install 1 of N CRD bundles alongside the operator yaml. The main disadvantage there being that the users then need to remember to install the updated versions of those CRDs every release, which if they used `--crdPattern` would just work automatically.

**Comment by jackfrancis** [comment]
My intuition says:

1) Update the controller so "empty --crd-pattern" + "no existing CRDs" doesn't exit non-zero. Strictly from a runtime perspective, a continual reconciler with no work to do is not an anti-pattern. A simple log statement would clarify for naive users why the pod isn't doing anything or why CRDs aren't present on the system.
2) Continue to recommend that helm be the canonical package for installing ASO
3) Explicitly state in install docs that `--set values.crdPattern=<insert example CRDs here>` is The Way
4) If we wanna provide a "raw YAML" install flow I'd probably make it clear that you want to do a more complicated one-liner w/ the desired CRD set (envsubst or something). Maybe you could actually make the variable string (e.g., $CRD-PATTERN) a well known sentinel in the runtime itself so that you don't have to publish a seprate "raw" YAML for the env-aware flavor? So in case a user ignores the documentation and installs it w/ a simple kubectl apply the runtime can interpret "$CRD-PATTERN" as a literal string with the equivalent value of "" (empty string)?

For me the main sticking point has to do with easily discovering which vals to pus into any of the above options. Is there an easy discovery mechanism for producing a workable --crd-patttern string that I can pass to helm or envsubst?

**Comment by theunrepentantgeek** [comment]
I'm acutely conscious of the new user experience - if ASO sits there "doing nothing" (because of no configuration), a new user may not think to check the logs, instead concluding that it simply doesn't work and moving on. 

Think of it this way: You're visiting a car dealer and jump in a car for a test drive. When you turn the key to start the car, nothing happens. Do you try to troubleshoot and discover the battery is disconnected? Or do you instead jump into a different car. 

> s there an easy discovery mechanism for producing a workable --crd-patttern string that I can pass to helm or envsubst?

I'm not sure if it qualifies as _easy discovery_, but the patterns are documented for each group. E.g., for [KeyVault](https://azure.github.io/azure-service-operator/reference/keyvault/):

> To install the CRDs for these resources, your ASO configuration must include `keyvault.azure.com/*` as a one of the configured CRD patterns. See [CRD Management in ASO](https://azure.github.io/azure-service-operator/guide/crd-management/) for details on doing this for both [Helm](https://azure.github.io/azure-service-operator/guide/crd-management/#helm) and [YAML](https://azure.github.io/azure-service-operator/guide/crd-management/#yaml) based installations

Keen to hear any ideas you have to make these more discoverable.

**Comment by matthchr** [comment]
If we do put this into `asoctl`, we should support N `--crdPattern`.

--raw, which gives the raw file.
otherwise, has a required `--crdPattern`, but produces YAML that you then kubectl apply that.
