### ISSUE TITLE
Feature: ASOv2 lacking standalone server support for MySQL

### ISSUE THREAD

**Issue by bwiens** [Azure/azure-service-operator#3786]
ASOv1 only supports MYSQL standalone. In order to migrate from ASOv1 to ASOv2, there needs to be standalone server support for MySQL in ASOv2. Thank you.

**Comment by matthchr** [comment]
Note to ourselves: When we do this, we want to make sure to note in the doc fragment for the MySQL standalone that it will be deprecated around Sept 2024 (include what ASO will do at this time w/ the CRD)

**Comment by theunrepentantgeek** [comment]
Looks like things start shutting down soon - quoting [What's happening to Azure Database for MySQL - Single Server?](https://learn.microsoft.com/en-us/azure/mysql/single-server/whats-happening-to-mysql-single-server):

> As part of this retirement, we will no longer support creating new Single Server instances from the Azure portal beginning **January 16, 2023**. Additionally, starting **March 19, 2024** you will no longer be able to create new Azure Database for MySQL Single Server instances using Azure CLI. If you still need to create Single Server instances to meet business continuity needs, raise an Azure support ticket.

**Comment by bwiens** [comment]
Hi @matthchr @theunrepentantgeek: I wanted to ask why you had me create this feature request. While on ASOv1 MYSQL Standalone, can we add skip-reconcile, migrate to flexible, and adopt with v2? Or is the time for this approach too long? For a while, we will run ASOv1 side-by-side with ASOv2.

**Comment by matthchr** [comment]
We're not 100% going to do this I just wanted to make sure we at least consider doing it.

let me ask you this: Are you OK with doing the following?
> While on ASOv1 MYSQL Standalone, can we add skip-reconcile, migrate to flexible, and adopt with v2?

It will work, and is easier for us (because we don't have to support Standalone which is near end of life). If you're happy with this being the flow, I think we can probably close this item (I am not aware of other customers using MySQL Standalone in ASOv1 still, but if they are they can follow the same process).

What additional support (if any) from ASO do you want/need to make the above work? Concrete v1 -> v2 migration guide? Anything else?

**Comment by matthchr** [comment]
Thanks for filing this.

As discussed above and pointed out by @theunrepentantgeek, since MySQL standalone server is blocking new creates starting now (well, 10 days ago), I think it makes the most sense to follow the process mentioned above to migrate from Single Server to flex and then import the flex into ASOv2.

I've written up a little blurb about how to do this in #3898. Going to go ahead and close this.
