### ISSUE TITLE
Add support for reading `name` or `armId` in all `KnownResourceReference` fields from Secrets and ConfigMaps

### ISSUE THREAD

**Issue by bernardhalas** [Azure/azure-service-operator#3827]
**Describe the current behavior**
The owner ref (e.g. `StorageAccount.spec.owner` in `storage.azure.com/v1api20230101`) doesn't support the references to values stored in Secrets or ConfigMaps.

An example scenario: DevOps engineers/admins deploy ASO + namespace + create a subscription for developers, to give them the ability to provision Azure resources in a K8s-native way easily. The admins store the environment context in Secrets or ConfigMaps and hand the environment over to the users. In that case, it seems useful to support references in all the fields that are of type [`genruntime.KnownResourceReference`](https://pkg.go.dev/github.com/Azure/azure-service-operator/v2/pkg/genruntime#KnownResourceReference), like the `.spec.owner` in StorageAccount, so that the users of the environment do not need to know the values of the known resources (like subnet IDs, subscription IDs, etc.), but instead, can simply reference them in the existing resources.

This would also allow the users of the environment to create packages that can be reused across different environments/subscriptions/subnet ids, etc.

**Describe the improvement**
Add support for `secretRef` and `configMap` references to `genruntime.KnownResourceReference`.

**Comment by matthchr** [comment]
For configuration management details, where the values are statically known prior to deployment, we strongly recommend people using existing tools such as Helm, Kustomize, or <insert-favorite-tool-here>. The  secret and config map features in ASO are generally intended for dynamic values that aren't known prior to deployment - such as service endpoints and API keys generated by Azure.

> The admins store the environment context in Secrets or ConfigMaps and hand the environment over to the users. In that case, it seems useful to support references in all the fields that are of type [genruntime.KnownResourceReference](https://pkg.go.dev/github.com/Azure/azure-service-operator/v2/pkg/genruntime#KnownResourceReference), like the .spec.owner in StorageAccount, so that the users of the environment do not need to know the values of the known resources (like subnet IDs, subscription IDs, etc.), but instead, can simply reference them in the existing resources.

You can import that vnet/subnet into the namespace and stick a [reconcile-policy: skip](https://azure.github.io/azure-service-operator/guide/annotations/#serviceoperatorazurecomreconcile-policy) annotation on it, so that users in that namespace can refer to it by its Kubernetes name as well. This has the advantage of letting them examine those resources in a Kubernetes native way too, just like they can with the resources they're managing.

OTOH if what you're looking for is a way to _force_ developers to use a certain set of values, something like Azure Policy or OPA/Gatekeeper might be what you're looking for.

**Comment by bernardhalas** [comment]
Thanks for the response @matthchr . Before closing this issue, I'll just add more information that might be handy to the next person having similar question.

1. [how to import resources](https://azure.github.io/azure-service-operator/guide/frequently-asked-questions/#how-can-i-import-existing-azure-resources-into-aso)
1. [how to reference imported resources](https://azure.github.io/azure-service-operator/guide/frequently-asked-questions/#whats-the-difference-between-aso-and-crossplaneio)
_In ASO, you can specify the raw ARM ID but you can also specify a reference to the corresponding resource in Kubernetes (with its Kubernetes name) and ASO translates that into an ARM ID under the hood so that you don’t have to._
