### ISSUE TITLE
Bug: RoleAssignmentProperties.DelegatedManagedIdentityResourceId has wrong type

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3831]
**Describe the bug**

As discussed in #3772 the property`RoleAssignmentProperties.DelegatedManagedIdentityResourceId` from the `authorization` group has the wrong type.

Unlike the other groups identified in that issue, there is no newer version of `authorization` to import, so we can't fix this with a non-breaking change. 

What should we do?

**Comment by matthchr** [comment]
I wonder if there's any way for us to know how much usage this property has today? I _think_ that's a pretty esoteric property... we could take a break but if would be good to know it had no usage (or very low usage) before we did.

OTOH we could live with it as it is, under the philosophy "better to not break users". Since nobody is complaining about this right now it may not be a huge issue?

Thoughts?
