### ISSUE TITLE
Disk resource does not support "Premium_ZRS" and few other sku's

### ISSUE THREAD

**Issue by ganeshg2491** [Azure/azure-service-operator#4057]
**Describe the current behavior**
Currently Disk resource is generated from " /compute/resource-manager/Microsoft.Compute/DiskRP/stable/2020-09-30/disk.json"
and it does not seem to be supported all the mention ZRS sku's in
https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/disks?pivots=deployment-language-arm-template#disksku-1

**Describe the improvement**
Disk resource needs to be regenerated from the latest arm api version "2023-10-02".

**Additional context**
Add any other context about the suggested improvement.

**Comment by theunrepentantgeek** [comment]
We'll look into adding support for api-version 2023-10-02 - this will sit alongside the existing version, allowing users to update on their schedule, not ours.

**Comment by ganeshg2491** [comment]
@theunrepentantgeek : Thanks. As a part of this change, can we also support including "Microsoft.Compute/diskAccesses" and "Microsoft.Compute/diskAccesses/privateEndpointConnections" resource which is require for Disk private access.

**Comment by matthchr** [comment]
The above PR resolves this, with one exception.

We added `Microsoft.Compute/diskAccesses`, but did _not_ add `Microsoft.Compute/diskAccesses/privateEndpointConnections`. This is because the `privateEndpointConnections` resource is only used to approve `privateEndpoints`.

Our current thinking with this scenario is either:
1. You're autoapproved, in which case you don't need `Microsoft.Compute/diskAccesses/privateEndpointConnections`.
2. You're _not_ autoapproved, in which case the connection likely needs to be reviewed by a person (not managed through IAC), in which case using something like portal or azcli for the approval probably makes more sense than managing it through ASO.

Let us know if you agree/disagree with that sentiment. Other than that though, all your asks are actioned by the linked PR.

**Comment by ganeshg2491** [comment]
@matthchr : Yeah, I think that's fine. Good to go ahead with this PR.
